create extension if not exists pgcrypto with schema extensions;

create table if not exists public.devfit_security_events (
  id bigint generated by default as identity primary key,
  email text,
  device_hash text check (device_hash is null or device_hash ~ '^[0-9a-f]{64}$'),
  ip_hash text check (ip_hash is null or ip_hash ~ '^[0-9a-f]{64}$'),
  event_type text not null check (char_length(event_type) between 3 and 50),
  severity text not null default 'warning' check (severity in ('info', 'warning', 'high')),
  route text not null default '' check (char_length(route) <= 120),
  reason text not null default '' check (char_length(reason) <= 500),
  blocked boolean not null default false,
  at timestamptz not null default now()
);

create index if not exists devfit_security_events_at_idx
  on public.devfit_security_events (at desc);
create index if not exists devfit_security_events_email_at_idx
  on public.devfit_security_events (email, at desc);

create table if not exists public.devfit_security_blocks (
  id uuid primary key default gen_random_uuid(),
  scope text not null check (scope in ('account', 'device', 'ip')),
  key_hash text not null check (key_hash ~ '^[0-9a-f]{64}$'),
  email text,
  reason text not null check (char_length(reason) between 3 and 500),
  active boolean not null default true,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  created_by text not null default 'owner',
  released_at timestamptz,
  unique (scope, key_hash)
);

create index if not exists devfit_security_blocks_active_idx
  on public.devfit_security_blocks (scope, active, expires_at);
create index if not exists devfit_security_blocks_email_idx
  on public.devfit_security_blocks (email, created_at desc);

alter table public.devfit_security_events enable row level security;
alter table public.devfit_security_blocks enable row level security;

revoke all on table public.devfit_security_events from public, anon, authenticated;
revoke all on table public.devfit_security_blocks from public, anon, authenticated;
grant select, insert, update, delete on table public.devfit_security_events to service_role;
grant select, insert, update, delete on table public.devfit_security_blocks to service_role;
revoke all on sequence public.devfit_security_events_id_seq from public, anon, authenticated;
grant usage, select on sequence public.devfit_security_events_id_seq to service_role;

-- Explicit deny policies document the intended browser boundary and make a
-- future accidental table grant harmless. DevFit's Vercel API uses service_role.
drop policy if exists devfit_security_events_deny_browser on public.devfit_security_events;
create policy devfit_security_events_deny_browser on public.devfit_security_events
  for all to anon, authenticated using (false) with check (false);
drop policy if exists devfit_security_blocks_deny_browser on public.devfit_security_blocks;
create policy devfit_security_blocks_deny_browser on public.devfit_security_blocks
  for all to anon, authenticated using (false) with check (false);

-- These existing service-only tables intentionally had no policies. Add an
-- explicit deny policy so their safety remains obvious and advisor-friendly.
drop policy if exists devfit_payments_deny_browser on public.devfit_payments;
create policy devfit_payments_deny_browser on public.devfit_payments
  for all to anon, authenticated using (false) with check (false);
drop policy if exists devfit_support_requests_deny_browser on public.devfit_support_requests;
create policy devfit_support_requests_deny_browser on public.devfit_support_requests
  for all to anon, authenticated using (false) with check (false);

create or replace function public.check_devfit_security_access(
  p_email text,
  p_device_id text,
  p_ip_hash text,
  p_user_agent text,
  p_route text,
  p_register boolean default false,
  p_is_login boolean default false,
  p_require_known boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
  v_email text := lower(trim(coalesce(p_email, '')));
  v_device text := trim(coalesce(p_device_id, ''));
  v_ip_hash text := lower(trim(coalesce(p_ip_hash, '')));
  v_account_hash text;
  v_device_hash text;
  v_existing public.devfit_logins%rowtype;
  v_active_devices integer := 0;
  v_status text := 'ok';
begin
  if v_email = '' or char_length(v_email) > 254 or position('@' in v_email) <= 1 then
    return jsonb_build_object('status', 'invalid_account');
  end if;
  if char_length(v_device) < 16 or char_length(v_device) > 80 then
    return jsonb_build_object('status', 'invalid_device');
  end if;
  if v_ip_hash <> '' and v_ip_hash !~ '^[0-9a-f]{64}$' then
    return jsonb_build_object('status', 'invalid_request');
  end if;

  v_account_hash := encode(extensions.digest(v_email, 'sha256'), 'hex');
  v_device_hash := encode(extensions.digest(v_device, 'sha256'), 'hex');

  if exists (
    select 1 from public.devfit_security_blocks
    where scope = 'account' and key_hash = v_account_hash and active
      and (expires_at is null or expires_at > now())
  ) then v_status := 'account_blocked';
  elsif exists (
    select 1 from public.devfit_security_blocks
    where scope = 'device' and key_hash = v_device_hash and active
      and (expires_at is null or expires_at > now())
  ) then v_status := 'device_blocked';
  elsif v_ip_hash <> '' and exists (
    select 1 from public.devfit_security_blocks
    where scope = 'ip' and key_hash = v_ip_hash and active
      and (expires_at is null or expires_at > now())
  ) then v_status := 'ip_blocked';
  end if;

  if v_status <> 'ok' then
    if not exists (
      select 1 from public.devfit_security_events
      where email = v_email and event_type = v_status and at > now() - interval '5 minutes'
    ) then
      insert into public.devfit_security_events
        (email, device_hash, ip_hash, event_type, severity, route, reason, blocked)
      values
        (v_email, v_device_hash, nullif(v_ip_hash, ''), v_status, 'high', left(coalesce(p_route,''),120),
         'Request denied by an active owner block', true);
    end if;
    return jsonb_build_object('status', v_status, 'deviceHash', v_device_hash);
  end if;

  select * into v_existing from public.devfit_logins
    where email = v_email and device_id = v_device;

  if p_require_known and v_existing.email is null then
    return jsonb_build_object('status', 'unknown_device', 'deviceHash', v_device_hash);
  end if;

  select count(*) into v_active_devices from public.devfit_logins
    where email = v_email and last_seen >= now() - interval '45 days';

  -- Grandfather devices already used by an account. Only an additional new
  -- device is denied, so rollout never ejects a legitimate current device.
  if v_existing.email is null and p_register and v_active_devices >= 3 then
    if not exists (
      select 1 from public.devfit_security_events
      where email = v_email and device_hash = v_device_hash
        and event_type = 'device_limit' and at > now() - interval '30 minutes'
    ) then
      insert into public.devfit_security_events
        (email, device_hash, ip_hash, event_type, severity, route, reason, blocked)
      values
        (v_email, v_device_hash, nullif(v_ip_hash, ''), 'device_limit', 'high', left(coalesce(p_route,''),120),
         'A fourth active device attempted to use this account', true);
    end if;
    return jsonb_build_object('status', 'device_limit', 'deviceHash', v_device_hash,
      'activeDevices', v_active_devices, 'maxDevices', 3);
  end if;

  if p_register then
    insert into public.devfit_logins
      (email, device_id, user_agent, first_seen, last_seen, login_count)
    values
      (v_email, v_device, left(coalesce(p_user_agent,''),300), now(), now(), 1)
    on conflict (email, device_id) do update set
      user_agent = excluded.user_agent,
      last_seen = now(),
      login_count = public.devfit_logins.login_count + case when p_is_login then 1 else 0 end;
  end if;

  -- Retain useful security history without unlimited table growth.
  delete from public.devfit_security_events where at < now() - interval '180 days';

  return jsonb_build_object('status', 'ok', 'deviceHash', v_device_hash,
    'activeDevices', case when v_existing.email is null and p_register then v_active_devices + 1 else v_active_devices end,
    'maxDevices', 3);
end;
$$;

revoke all on function public.check_devfit_security_access(text,text,text,text,text,boolean,boolean,boolean)
  from public, anon, authenticated;
grant execute on function public.check_devfit_security_access(text,text,text,text,text,boolean,boolean,boolean)
  to service_role;

create or replace function public.reset_devfit_devices(p_email text)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_email text := lower(trim(coalesce(p_email, '')));
  v_count integer;
begin
  if v_email = '' or position('@' in v_email) <= 1 then raise exception 'invalid email'; end if;
  delete from public.devfit_logins where email = v_email;
  get diagnostics v_count = row_count;
  insert into public.devfit_security_events (email, event_type, severity, route, reason, blocked)
  values (v_email, 'devices_reset', 'info', '/api/admin', 'Owner reset trusted devices', false);
  return v_count;
end;
$$;

revoke all on function public.reset_devfit_devices(text) from public, anon, authenticated;
grant execute on function public.reset_devfit_devices(text) to service_role;

create or replace function public.delete_devfit_account(p_email text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_email text := lower(trim(p_email));
  v_subscribers integer;
  v_current_data integer;
  v_versions integer;
  v_devices integer;
  v_records integer;
  v_payments integer;
  v_support integer;
  v_security_events integer;
  v_security_blocks integer;
begin
  if v_email = '' or position('@' in v_email) = 0 then raise exception 'invalid email'; end if;

  select count(*) into v_subscribers from public.devfit_subscribers where email = v_email;
  select count(*) into v_current_data from public.devfit_data where email = v_email;
  select count(*) into v_versions from public.devfit_data_versions where email = v_email;
  select count(*) into v_devices from public.devfit_logins where email = v_email;
  select count(*) into v_records from public.devfit_records where email = v_email;
  select count(*) into v_payments from public.devfit_payments where email = v_email;
  select count(*) into v_support from public.devfit_support_requests where email = v_email;
  select count(*) into v_security_events from public.devfit_security_events where email = v_email;
  select count(*) into v_security_blocks from public.devfit_security_blocks where email = v_email;

  delete from public.devfit_security_events where email = v_email;
  delete from public.devfit_security_blocks where email = v_email;
  delete from public.devfit_support_requests where email = v_email;
  delete from public.devfit_payments where email = v_email;
  delete from public.devfit_records where email = v_email;
  delete from public.devfit_data_versions where email = v_email;
  delete from public.devfit_data where email = v_email;
  delete from public.devfit_logins where email = v_email;
  delete from public.devfit_subscribers where email = v_email;

  return jsonb_build_object(
    'email', v_email, 'subscribers', v_subscribers, 'currentData', v_current_data,
    'recoveryVersions', v_versions, 'devices', v_devices, 'records', v_records,
    'payments', v_payments, 'supportRequests', v_support,
    'securityEvents', v_security_events, 'securityBlocks', v_security_blocks
  );
end;
$$;

revoke all on function public.delete_devfit_account(text) from public, anon, authenticated;
grant execute on function public.delete_devfit_account(text) to service_role;

comment on table public.devfit_security_events is
  'Privacy-minimised authentication and abuse events retained for 180 days.';
comment on table public.devfit_security_blocks is
  'Owner-managed account, device and IP blocks; keys are SHA-256 hashes.';
